"""
Deterministic sandbox behind every Execution Type explanation in the UI.

The single rule this module exists to enforce: **explanatory copy is generated by
running the real engine, never by re-describing it.** Every number the dashboard
shows about an execution mode — the inline "first entry ≈ $x" previews, the
mechanics matrix footnotes, the mode fingerprints, the predict-then-reveal
answer — comes out of :func:`simulate`, which calls :func:`lib.strategy.backtest`
on a fixed synthetic tape.

This is not incidental. The captions this module replaces ("Buy 100%, then sell
100%", "Trade % of portfolio per signal") were hand-written descriptions of the
engine that silently drifted from it: Trading's first entry is ~4.2% of the
account, not 100%, and Rebalancing used to size off cash and off units held
rather than off portfolio value. Any explainer that hardcodes its own arithmetic
re-introduces exactly that failure mode on the first engine change.

Nothing here touches the network, the config, or the clock.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any, Mapping

import numpy as np
import pandas as pd

from lib.strategy import backtest

# Fallback only. The dashboard has a real ``initial-capital`` input (defaulting to
# dash_config.INITIAL_CAPITAL), and callers pass that through as ``capital`` so
# the previews quote the user's own account size rather than a stand-in.
SANDBOX_CAPITAL = 10_000.0

BUY_COLUMN = 'Sandbox_Buy'
SELL_COLUMN = 'Sandbox_Sell'

# Costs are zeroed so the sandbox teaches *sizing*, which is what the modes
# actually differ on. Fees would add pennies of drift to every row and make the
# ledger arithmetic harder to follow without changing any conclusion.
_SANDBOX_COSTS = {
    'commission_per_trade': 0.0,
    'slippage_pct': 0.0,
    'fx_fee_pct': 0.0,
}

# 24 bars: a rally, a drawdown deep enough to trip a trailing stop, then a
# recovery. Round numbers so a reader can verify the arithmetic by hand.
_SANDBOX_CLOSES: tuple[float, ...] = (
    100.0, 102.0, 105.0, 104.0, 108.0, 112.0, 115.0, 118.0,
    120.0, 116.0, 110.0, 104.0, 98.0, 94.0, 90.0, 92.0,
    96.0, 100.0, 104.0, 108.0, 110.0, 114.0, 118.0, 120.0,
)

# Signal bars are chosen so every mode has something to show: buys clustered in
# the rally (so scale-in ramps visibly), buys during the dip (so DCA averages
# down), and sells on the way up and the way down.
_BUY_BARS: tuple[int, ...] = (0, 4, 9, 12, 15, 19)
_SELL_BARS: tuple[int, ...] = (7, 17, 21)


@dataclass(frozen=True)
class LedgerRow:
    """One bar of the sandbox, in the terms a reader cares about."""

    bar: int
    price: float
    signal: str          # 'buy' | 'sell' | ''
    action: str          # human phrase, e.g. 'bought $1,667'
    order_value: float   # signed: + bought, - sold, 0 nothing happened
    units: float
    cash: float
    equity: float
    note: str = ''       # why nothing happened, when nothing happened


@dataclass(frozen=True)
class SandboxRun:
    """Everything the teaching UI needs from one pass of the engine."""

    mode: str
    params: Mapping[str, Any]
    capital: float
    rows: tuple[LedgerRow, ...]
    equity: tuple[float, ...]
    first_entry_value: float
    first_entry_pct: float
    buy_count: int
    sell_count: int
    stop_exits: int
    final_equity: float
    total_return_pct: float
    ever_fully_exited: bool
    extras: Mapping[str, Any] = field(default_factory=dict)


def build_sandbox_frame() -> pd.DataFrame:
    """The fixed tape. Same shape the engine gets from a real data load."""
    close = np.asarray(_SANDBOX_CLOSES, dtype=float)
    n = len(close)
    buy = np.zeros(n, dtype=int)
    sell = np.zeros(n, dtype=int)
    buy[list(_BUY_BARS)] = 1
    sell[list(_SELL_BARS)] = 1

    return pd.DataFrame(
        {
            'Open': close,
            'High': close * 1.01,
            'Low': close * 0.99,
            'Close': close,
            'Volume': np.full(n, 1_000_000),
            BUY_COLUMN: buy,
            SELL_COLUMN: sell,
        },
        index=pd.date_range('2024-01-01', periods=n, freq='B'),
    )


def default_params(mode: str) -> dict[str, Any]:
    """Sandbox starting knobs per mode, matching the dashboard's own defaults."""
    common = {
        'min_holding_period': 0,
        'trailing_stop_pct': 15.0,
        'take_profit_pct': 0.0,
        'capital': SANDBOX_CAPITAL,
    }
    if mode == 'accumulation':
        return {**common, 'amount_per_buy': 1_000.0}
    if mode == 'rebalancing':
        return {**common, 'position_size_pct': 25.0}
    return {
        **common,
        'kelly_win_rate': 0.5,
        'kelly_win_loss_ratio': 1.5,
        'position_scaling_pct': 100.0,
    }


def _money(value: float) -> str:
    return f"${value:,.0f}"


def _build_rows(result: pd.DataFrame, mode: str) -> tuple[LedgerRow, ...]:
    """Turn the engine's result frame into reader-facing ledger rows."""
    rows: list[LedgerRow] = []
    close = result['Close'].to_numpy(dtype=float)
    bought = result['Units_to_buy'].to_numpy(dtype=float)
    sold = result['Units_to_sell'].to_numpy(dtype=float)
    units = result['Units'].to_numpy(dtype=float)
    cash = result['Cash_Value'].to_numpy(dtype=float)
    equity = result['Portfolio_Value'].to_numpy(dtype=float)

    buy_raw = result[BUY_COLUMN].to_numpy(dtype=float)
    sell_raw = result[SELL_COLUMN].to_numpy(dtype=float)

    prev_units = 0.0
    for i in range(len(close)):
        # Signals are lagged by one bar, so the signal that *caused* bar i's fill
        # was printed on bar i-1. Report the cause next to its effect.
        signalled_buy = bool(buy_raw[i - 1]) if i > 0 else False
        signalled_sell = bool(sell_raw[i - 1]) if i > 0 else False

        signal = 'buy' if signalled_buy else ('sell' if signalled_sell else '')
        order_value = 0.0
        action = '—'
        note = ''

        if bought[i] > 0:
            order_value = bought[i] * close[i]
            action = f"bought {_money(order_value)}"
        elif sold[i] > 0:
            order_value = -sold[i] * close[i]
            action = f"sold {_money(-order_value)}"
            if prev_units > 0 and units[i] <= 1e-9 and not signalled_sell:
                action += " (stop)"
                note = 'trailing stop'
        elif signalled_sell and mode == 'accumulation':
            note = 'sell signals are ignored in this mode'
        elif signalled_buy and cash[i] <= 1e-9:
            note = 'out of cash'

        rows.append(
            LedgerRow(
                bar=i,
                price=float(close[i]),
                signal=signal,
                action=action,
                order_value=float(order_value),
                units=float(units[i]),
                cash=float(cash[i]),
                equity=float(equity[i]),
                note=note,
            )
        )
        prev_units = float(units[i])

    return tuple(rows)


@lru_cache(maxsize=64)
def _simulate_cached(mode: str, param_items: tuple[tuple[str, Any], ...]) -> SandboxRun:
    params = dict(param_items)
    capital = float(params.get('capital') or SANDBOX_CAPITAL)
    df = build_sandbox_frame()

    # Accumulation is the one mode with no sell side at all; handing the engine an
    # empty sell list mirrors what callbacks/backtest.py does for it.
    sell_indicators = [] if mode == 'accumulation' else [SELL_COLUMN]

    if mode == 'accumulation':
        sizing_strategy, sizing_params = 'percentage_of_portfolio', {'percent': 100.0}
    elif mode == 'rebalancing':
        sizing_strategy, sizing_params = 'percentage_of_portfolio', {'percent': 100.0}
    else:
        sizing_strategy = 'kelly_criterion'
        sizing_params = {
            'win_rate': float(params.get('kelly_win_rate', 0.5)),
            'win_loss_ratio': float(params.get('kelly_win_loss_ratio', 1.5)),
        }

    result = backtest(
        df=df,
        initial_capital=capital,
        position_sizing_strategy=sizing_strategy,
        position_sizing_params=sizing_params,
        buy_indicators=[BUY_COLUMN],
        sell_indicators=sell_indicators,
        strategy_mode=mode,
        amount_per_buy=float(params.get('amount_per_buy', 1_000.0)),
        position_size_pct=float(params.get('position_size_pct', 25.0)),
        position_scaling=float(params.get('position_scaling_pct', 100.0)) / 100.0,
        min_holding_period=int(params.get('min_holding_period', 0)),
        trailing_stop_loss=float(params.get('trailing_stop_pct', 15.0)) / 100.0,
        take_profit=float(params.get('take_profit_pct', 0.0)) / 100.0,
        allow_fractional=True,
        **_SANDBOX_COSTS,
    )

    rows = _build_rows(result, mode)
    equity = tuple(float(v) for v in result['Portfolio_Value'].to_numpy())

    buys = [r for r in rows if r.order_value > 0]
    sells = [r for r in rows if r.order_value < 0]
    first_entry = buys[0].order_value if buys else 0.0

    trades = result.attrs.get('trades')
    stop_exits = 0
    if trades is not None and not trades.empty and 'exit_reason' in trades:
        stop_exits = int((trades['exit_reason'] == 'trailing_stop').sum())

    return SandboxRun(
        mode=mode,
        params=params,
        capital=capital,
        rows=rows,
        equity=equity,
        first_entry_value=first_entry,
        first_entry_pct=first_entry / capital if capital else 0.0,
        buy_count=len(buys),
        sell_count=len(sells),
        stop_exits=stop_exits,
        final_equity=equity[-1] if equity else capital,
        total_return_pct=(equity[-1] / capital - 1.0) * 100 if equity else 0.0,
        ever_fully_exited=any(r.units <= 1e-9 for r in rows[1:]),
    )


def simulate(mode: str, **params: Any) -> SandboxRun:
    """Run the fixed tape through the real engine for *mode*.

    Results are cached on the parameter tuple, so slider drags in the sandbox are
    cheap and repeated renders are free.
    """
    merged = {**default_params(mode), **{k: v for k, v in params.items() if v is not None}}
    return _simulate_cached(mode, tuple(sorted(merged.items())))


def first_entry_summary(mode: str, **params: Any) -> str:
    """One honest line about what the first buy signal actually does.

    This is what the mode cards show inline, replacing captions that claimed
    behaviour the engine never had.
    """
    run = simulate(mode, **params)
    if run.first_entry_value <= 0:
        return "no entry — check capital and sizing"

    if mode == 'accumulation':
        per_buy = float(run.params.get('amount_per_buy') or 1_000.0)
        affordable = int(run.capital // per_buy) if per_buy > 0 else 0
        return f"{_money(per_buy)} per buy · {affordable} buys until cash runs out"
    return (
        f"first entry ≈ {_money(run.first_entry_value)} "
        f"({run.first_entry_pct:.1%} of {_money(run.capital)})"
    )
