"""
Dashboard Styles
Style generators for dashboard components.

The bulk of theming lives in `lib/dash/assets/dashboard.css` (auto-loaded by
Dash) using CSS variables. This module provides Python-side inline style
dicts that consume the active theme palette directly — used where Dash
components only accept inline `style=` props.
"""

from lib.dash.dash_config import (
    FONT_FAMILY, FONT_SIZES, BORDER_RADIUS,
    SIDEBAR_WIDTH, RIGHT_PANEL_WIDTH, HEADER_HEIGHT,
)


def get_styles(theme: dict) -> dict:
    """Generate inline styles based on the active theme palette."""
    return {
        'app': {
            'fontFamily': FONT_FAMILY,
            'backgroundColor': theme['bg_primary'],
            'color': theme['text_primary'],
            'minHeight': '100vh',
            'margin': 0,
            'padding': 0,
            'fontSize': FONT_SIZES['sm'],
        },
        'header': {
            'backgroundColor': theme['bg_secondary'],
            'borderBottom': f'1px solid {theme["border_primary"]}',
            'display': 'flex',
            'alignItems': 'center',
            'justifyContent': 'space-between',
            'gap': '14px',
            'height': HEADER_HEIGHT,
            'padding': '0 14px',
        },
        'logo': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '12px',
        },
        'logo_icon': {
            'fontFamily': FONT_FAMILY,
            'fontSize': '14px',
            'fontWeight': 700,
            'color': theme['accent_blue'],
            'letterSpacing': '2px',
        },
        'logo_text': {
            'fontFamily': FONT_FAMILY,
            'fontSize': '10px',
            'fontWeight': 500,
            'color': theme['text_tertiary'],
            'letterSpacing': '2px',
            'textTransform': 'uppercase',
            'borderLeft': f'1px solid {theme["border_primary"]}',
            'paddingLeft': '12px',
        },
        'header_controls': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '12px',
        },
        'header_tape': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '14px',
            'fontFamily': FONT_FAMILY,
            'fontSize': '13px',
            'flex': 1,
            'justifyContent': 'center',
        },
        'main_container': {
            'display': 'flex',
            'height': f'calc(100vh - {HEADER_HEIGHT} - 24px)',
            'overflow': 'hidden',
            'minWidth': 0,
        },
        'sidebar': {
            'width': SIDEBAR_WIDTH,
            'minWidth': SIDEBAR_WIDTH,
            'backgroundColor': theme['bg_panel'],
            'borderRight': f'1px solid {theme["border_primary"]}',
            'display': 'flex',
            'flexDirection': 'column',
            'gap': '6px',
            'padding': '8px',
            'position': 'relative',
            'zIndex': 3,
            'overflowY': 'auto',
            'overflowX': 'hidden',
        },
        'sidebar_section': {
            'backgroundColor': theme['bg_tertiary'],
            'border': f'1px solid {theme["border_primary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'padding': '8px 10px',
        },
        'help_icon': {
            'display': 'inline-flex',
            'alignItems': 'center',
            'justifyContent': 'center',
            'width': '14px',
            'height': '14px',
            'borderRadius': '50%',
            'border': f'1px solid {theme["border_secondary"]}',
            'color': theme['text_secondary'],
            'fontSize': '10px',
            'fontWeight': '600',
            'cursor': 'help',
            'marginLeft': '6px',
            'fontFamily': FONT_FAMILY,
        },
        'indicator_label_row': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '8px',
            'width': '100%',
        },
        'indicator_row': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '8px',
            'width': '100%',
        },
        'indicator_gear_button': {
            'marginLeft': 'auto',
            'backgroundColor': 'transparent',
            'border': f'1px solid {theme["border_secondary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'color': theme['text_secondary'],
            'fontSize': '11px',
            'width': '20px',
            'height': '20px',
            'display': 'flex',
            'alignItems': 'center',
            'justifyContent': 'center',
            'cursor': 'pointer',
            'padding': 0,
            'pointerEvents': 'auto',
            'zIndex': 1,
            'fontFamily': FONT_FAMILY,
        },
        'indicator_gear_button_active': {
            'border': f'1px solid {theme["border_focus"]}',
            'color': theme['accent_blue'],
        },
        'indicator_settings_panel': {
            'display': 'flex',
            'flexDirection': 'column',
            'gap': '6px',
        },
        'indicator_setting_row': {
            'display': 'flex',
            'alignItems': 'center',
            'justifyContent': 'space-between',
            'gap': '10px',
        },
        'indicator_setting_label': {
            'fontSize': FONT_SIZES['xs'],
            'color': theme['text_secondary'],
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1px',
        },
        'indicator_setting_input': {
            'backgroundColor': theme['bg_secondary'],
            'border': f'1px solid {theme["border_primary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'color': theme['text_primary'],
            'padding': '4px 8px',
            'fontSize': FONT_SIZES['xs'],
            'fontFamily': FONT_FAMILY,
            'width': '100px',
            'height': '24px',
            'boxSizing': 'border-box',
        },
        'indicator_settings_empty': {
            'fontSize': FONT_SIZES['xs'],
            'color': theme['text_tertiary'],
            'padding': '4px 0',
            'fontFamily': FONT_FAMILY,
        },
        'sidebar_title': {
            'fontSize': FONT_SIZES['xs'],
            'fontWeight': '600',
            'color': theme['text_secondary'],
            'letterSpacing': '1.5px',
            'textTransform': 'uppercase',
            'marginBottom': '6px',
            'fontFamily': FONT_FAMILY,
        },
        'chart_container': {
            'flex': '1 1 0',
            'minWidth': 0,
            'minHeight': 0,
            'width': '100%',
            'display': 'flex',
            'flexDirection': 'column',
            'overflow': 'hidden',
            'backgroundColor': theme['bg_primary'],
            'position': 'relative',
            'zIndex': 1,
        },
        'chart_toolbar': {
            'display': 'flex',
            'alignItems': 'center',
            'justifyContent': 'space-between',
            'padding': '6px 10px',
            'minHeight': '36px',
            'height': 'auto',
            'backgroundColor': theme['bg_secondary'],
            'borderBottom': f'1px solid {theme["border_primary"]}',
            'gap': '10px',
            'flexWrap': 'wrap',
        },
        'chart_area': {
            'flex': '1 1 0',
            'minWidth': 0,
            'padding': '0',
            'overflow': 'hidden',
            'position': 'relative',
        },
        'signal_count_bar': {
            'display': 'flex',
            'alignItems': 'center',
            'gap': '8px',
            'padding': '4px 8px',
            'marginLeft': '12px',
            'backgroundColor': theme['bg_secondary'],
            'border': f'1px solid {theme["border_primary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'fontSize': FONT_SIZES['xs'],
            'color': theme['text_secondary'],
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1px',
            'flexShrink': 0,
        },
        'right_panel': {
            'width': RIGHT_PANEL_WIDTH,
            'minWidth': RIGHT_PANEL_WIDTH,
            'backgroundColor': theme['bg_panel'],
            'borderLeft': f'1px solid {theme["border_primary"]}',
            'display': 'flex',
            'flexDirection': 'column',
            'position': 'relative',
            'zIndex': 3,
            'overflow': 'hidden',
        },
        'panel_header': {
            'padding': '0',
            'borderBottom': f'1px solid {theme["border_primary"]}',
            'backgroundColor': theme['bg_secondary'],
            'display': 'flex',
            'alignItems': 'stretch',
        },
        'panel_title': {
            'fontSize': FONT_SIZES['sm'],
            'fontWeight': '600',
            'color': theme['text_primary'],
            'fontFamily': FONT_FAMILY,
        },
        'panel_content': {
            'flex': 1,
            'overflow': 'auto',
            'padding': '8px 10px',
            'backgroundColor': theme['bg_panel'],
            'color': theme['text_primary'],
        },
        'card': {
            'backgroundColor': theme['bg_tertiary'],
            'borderRadius': BORDER_RADIUS['sm'],
            'border': f'1px solid {theme["border_primary"]}',
            'marginBottom': '6px',
        },
        'card_header': {
            'padding': '6px 10px',
            'borderBottom': f'1px solid {theme["border_secondary"]}',
            'fontSize': FONT_SIZES['xs'],
            'fontWeight': '600',
            'color': theme['text_secondary'],
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1.5px',
        },
        'card_body': {
            'padding': '8px 10px',
            'color': theme['text_primary'],
        },
        'input': {
            'backgroundColor': theme['bg_secondary'],
            'border': f'1px solid {theme["border_primary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'color': theme['text_primary'],
            'padding': '5px 8px',
            'fontSize': FONT_SIZES['sm'],
            'fontFamily': FONT_FAMILY,
            'width': '100%',
            'height': '28px',
            'boxSizing': 'border-box',
        },
        'input_focus': {
            'borderColor': theme['border_focus'],
            'outline': 'none',
        },
        'button_primary': {
            'backgroundColor': theme['accent_blue'],
            'color': '#000',
            'border': 'none',
            'borderRadius': BORDER_RADIUS['sm'],
            'padding': '8px 14px',
            'fontSize': FONT_SIZES['sm'],
            'fontFamily': FONT_FAMILY,
            'fontWeight': '700',
            'textTransform': 'uppercase',
            'letterSpacing': '1.5px',
            'cursor': 'pointer',
            'transition': 'filter 100ms ease',
        },
        'button_success': {
            'backgroundColor': theme['accent_green'],
            'color': '#000',
            'border': 'none',
            'borderRadius': BORDER_RADIUS['sm'],
            'padding': '8px 14px',
            'fontSize': FONT_SIZES['sm'],
            'fontFamily': FONT_FAMILY,
            'fontWeight': '700',
            'textTransform': 'uppercase',
            'letterSpacing': '1.5px',
            'cursor': 'pointer',
        },
        'button_outline': {
            'backgroundColor': 'transparent',
            'color': theme['text_secondary'],
            'border': f'1px solid {theme["border_primary"]}',
            'borderRadius': BORDER_RADIUS['sm'],
            'padding': '4px 10px',
            'fontSize': FONT_SIZES['xs'],
            'fontFamily': FONT_FAMILY,
            'fontWeight': '500',
            'textTransform': 'uppercase',
            'letterSpacing': '1px',
            'cursor': 'pointer',
        },
        'metric_card': {
            'backgroundColor': theme['bg_tertiary'],
            'borderRadius': BORDER_RADIUS['sm'],
            'padding': '8px 10px',
            'marginBottom': '4px',
            'border': f'1px solid {theme["border_primary"]}',
        },
        'metric_label': {
            'fontSize': '10px',
            'color': theme['text_secondary'],
            'marginBottom': '4px',
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1.5px',
        },
        'metric_value': {
            'fontSize': FONT_SIZES['xl'],
            'fontWeight': '600',
            'color': theme['text_primary'],
            'fontFamily': FONT_FAMILY,
            'fontVariantNumeric': 'tabular-nums',
        },
        'metric_positive': {
            'color': theme['accent_green'],
        },
        'metric_negative': {
            'color': theme['accent_red'],
        },
        'checklist_container': {
            'display': 'flex',
            'flexDirection': 'column',
            'gap': '2px',
        },
        'checklist_item': {
            'display': 'flex',
            'alignItems': 'center',
            'padding': '4px 6px',
            'borderRadius': BORDER_RADIUS['sm'],
            'cursor': 'pointer',
            'transition': 'background-color 80ms ease',
            'color': theme['text_primary'],
            'fontSize': FONT_SIZES['xs'],
            'fontFamily': FONT_FAMILY,
        },
        'status_badge': {
            'display': 'inline-flex',
            'alignItems': 'center',
            'padding': '1px 6px',
            'borderRadius': BORDER_RADIUS['sm'],
            'fontSize': '10px',
            'fontWeight': '600',
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1px',
        },
        'status_success': {
            'backgroundColor': f'{theme["accent_green"]}20',
            'color': theme['accent_green'],
        },
        'status_warning': {
            'backgroundColor': f'{theme["accent_orange"]}20',
            'color': theme['accent_orange'],
        },
        'status_error': {
            'backgroundColor': f'{theme["accent_red"]}20',
            'color': theme['accent_red'],
        },
        'tab_container': {
            'display': 'flex',
            'borderBottom': f'1px solid {theme["border_primary"]}',
            'backgroundColor': theme['bg_secondary'],
        },
        'tab': {
            'padding': '8px 14px',
            'fontSize': FONT_SIZES['xs'],
            'color': theme['text_secondary'],
            'cursor': 'pointer',
            'borderBottom': '2px solid transparent',
            'transition': 'all 80ms ease',
            'fontFamily': FONT_FAMILY,
            'textTransform': 'uppercase',
            'letterSpacing': '1.5px',
            'fontWeight': '500',
        },
        'tab_active': {
            'color': theme['accent_blue'],
            'borderBottomColor': theme['accent_blue'],
            'fontWeight': '700',
        },
        'status_bar': {
            'display': 'flex',
            'alignItems': 'center',
            'height': '24px',
            'padding': '0 12px',
            'backgroundColor': theme['bg_secondary'],
            'borderTop': f'1px solid {theme["border_primary"]}',
            'fontFamily': FONT_FAMILY,
            'fontSize': '11px',
            'color': theme['text_secondary'],
            'letterSpacing': '0.5px',
            'flex': '0 0 24px',
        },
        'status_segment': {
            'display': 'inline-flex',
            'alignItems': 'center',
            'padding': '0 12px',
            'borderRight': f'1px solid {theme["border_primary"]}',
            'textTransform': 'uppercase',
            'whiteSpace': 'nowrap',
            'overflow': 'hidden',
            'textOverflow': 'ellipsis',
        },
    }


# Minimal extra CSS injected via index_string. The main stylesheet lives in
# lib/dash/assets/dashboard.css (auto-loaded by Dash), which uses CSS
# variables and handles theme switching via a body class. Anything kept
# here is safety duplication for environments where the assets folder
# hasn't been picked up yet.
CUSTOM_CSS = '''
/* Fallback resets in case assets/dashboard.css fails to load */
body { margin: 0; }
'''
